"""Pydantic models for the market-intelligence report.

`sections` holds shared primitives, `competitor` the per-brand nested models, `report`
the ten section models plus the root `MarketReport`, and `state` the LangGraph state.
"""

from __future__ import annotations

from .competitor import (
    AdCreativeSummary,
    AppStoreSignals,
    CompositeRetentionIndex,
    ContentMix,
    EngagementMetrics,
    EventRecord,
    FollowerSnapshot,
    HypeCyclePosition,
    PositioningMatrix2D,
    QualitativeProfile,
    RatingTrajectoryPoint,
    SeoSnapshot,
    StrategicMove,
    TrendMaturity,
    WebAnalytics,
)
from .report import (
    AppendixSection,
    BrandPositioning,
    CompetitiveLandscape,
    CompetitorProfile,
    ConsumerSignals,
    ExecutiveSummary,
    GlobalMarketLandscape,
    KPIDelta,
    MarketReport,
    MarketSizingPoint,
    MoMDiffStructured,
    QAIssue,
    QAVerdict,
    RegionalMarketPulse,
    Scoreboard,
    StrategicRecommendation,
    StrategicRecommendations,
    TechnologyTrends,
    TechTrendItem,
    TectonicShift,
)
from .sections import (
    CalloutSpec,
    ChartSpec,
    ConfidenceTier,
    KPITile,
    MonthlyValueSeries,
    ReportRef,
    SourceRef,
    TableSpec,
)
from .state import (
    ConductResearch,
    FactCheck,
    MarketReportState,
    ResearchComplete,
    ResearcherState,
    ResearchSupervisorState,
    override_reducer,
)

__all__ = [
    "AdCreativeSummary",
    "AppStoreSignals",
    "AppendixSection",
    "BrandPositioning",
    "CalloutSpec",
    "ChartSpec",
    "CompetitiveLandscape",
    "CompetitorProfile",
    "CompositeRetentionIndex",
    "ConductResearch",
    "ConfidenceTier",
    "ConsumerSignals",
    "ContentMix",
    "EngagementMetrics",
    "EventRecord",
    "ExecutiveSummary",
    "FactCheck",
    "FollowerSnapshot",
    "GlobalMarketLandscape",
    "HypeCyclePosition",
    "KPIDelta",
    "KPITile",
    "MarketReport",
    "MarketReportState",
    "MarketSizingPoint",
    "MoMDiffStructured",
    "MonthlyValueSeries",
    "PositioningMatrix2D",
    "QAIssue",
    "QAVerdict",
    "QualitativeProfile",
    "RatingTrajectoryPoint",
    "RegionalMarketPulse",
    "ReportRef",
    "ResearchComplete",
    "ResearchSupervisorState",
    "ResearcherState",
    "Scoreboard",
    "SeoSnapshot",
    "SourceRef",
    "StrategicMove",
    "StrategicRecommendation",
    "StrategicRecommendations",
    "TableSpec",
    "TectonicShift",
    "TechTrendItem",
    "TechnologyTrends",
    "TrendMaturity",
    "WebAnalytics",
    "override_reducer",
]
